### ISSUE TITLE
return protocol error on error

### ISSUE THREAD

**Issue by astrale-sharp** [taylorh140/pikchr-wasm-typst#2]
If the string provided to pickr isn't conform as to what is expected, 1 could be returned instead of 0 to warn typst that an error happened!

**Comment by taylorh140** [comment]
While this is true, I'm not sure how the error is propagated into typst. 
it would be best if i could show the error string that pikchr provides since it shows information about the error.
But yea this is possible and quite easy to do. 
I dont want rust to panic, i just want it to not produce a pdf and show the error.

**Comment by astrale-sharp** [comment]
typst (will) raise an error with the last string you sent to it `Plugin errored with: "..."`

**Comment by taylorh140** [comment]
I can do that.

**Comment by taylorh140** [comment]
![image](https://github.com/taylorh140/pikchr-wasm-typst/assets/10996543/88b31ad6-058b-403a-809d-2b0480873cd7)

formatting isn't pretty but it's something.

**Comment by taylorh140** [comment]
Ideally it would be more like:
```
/*   33 */  line same as D1 "F
/*   34 */  
/*   35 */  down
/*   36 */  move from C; 
/*   37 */  move
/*   38 */  oval "End"
                  ^^^
ERROR: syntax error
```

in this example i forgot a " after "F its a bit misleading but better than nothing.

**Comment by taylorh140** [comment]
I'm going to go ahead and close this. As the problem identified, I consider solved. However, I do realize there are new formatting issues, that might re-appear at some point.
